MagicVilla_Web_new/Controllers/VillaController.cs
using AutoMapper;
using MagicVilla_Web_new.Models;
using MagicVilla_Web_new.Models.Dto;
using MagicVilla_Web_new.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Runtime.CompilerServices;

namespace MagicVilla_Web_new.Controllers
{
    public class VillaController : Controller   
    {
        private readonly IVillaServices _villaServices;
        readonly IMapper _mapper;
        public VillaController(IVillaServices villaServices, IMapper mapper)
        {
            _villaServices = villaServices;
            _mapper = mapper;
            
        }

        public async Task<IActionResult> IndexVilla()
        {
            List<VillaDTO> list = new();
            var response = await _villaServices.GetAllAsync<APIResponse>();
            //if (response != null && response.IsSuccess)
            //{
                list = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result));

            //}
            return View(list);
        }
        public async Task<IActionResult> CreateVilla()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVilla(VillaCreateDTO model)
        {
            if (ModelState.IsValid) {
                var response = await _villaServices.CreatedAsynce<APIResponse>(model);
                return RedirectToAction(nameof(IndexVilla));

            }
            return View(model);
            

        }
        public async Task<IActionResult> UpdateVilla(int villaid)
        {
            //if (!ModelState.IsValid)
            //{
                var response = await _villaServices.GetAsync<APIResponse>(villaid);
                VillaDTO model = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result));
                return View(_mapper.Map<VillaUpdateDTO>(model));
            //}

            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVilla(VillaUpdateDTO model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaServices.UpdateAsync<APIResponse>(model);
                return RedirectToAction(nameof(IndexVilla));

            }
            return View(model);


        }


        //now for the delete
       
        public async Task<IActionResult> DeleteVilla(int villaid)
        {

            //var response = await _villaServices.GetAsync<APIResponse>(villaid);
            //VillaDTO model = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result));
            //return View(model);
            var response = await _villaServices.GetAsync<APIResponse>(villaid);
            if (response != null)
            {
                VillaDTO model = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound();



        }
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteVilla(VillaDTO model)
        //{

        //   // var response = await _villaServices.DeleteAsync<APIResponse>(model.Id);
        //    await _villaServices.RemoveAsync(model.Id); // Directly call RemoveAsync
        //    return RedirectToAction(nameof(IndexVilla));







        //}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteVillaConfirmed(VillaDTO model)
        {
           var response= await _villaServices.DeleteAsync<APIResponse>(model.Id);
         
            return RedirectToAction(nameof(IndexVilla));
        }
    }
    
}

MagicVilla_Web_new/Controllers/VillaNumberController.cs
using AutoMapper;
using MagicVilla_Web_new.Models;
using MagicVilla_Web_new.Models.Dto;
using MagicVilla_Web_new.Models.VM;
using MagicVilla_Web_new.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Cli.Utils;
using Newtonsoft.Json;

namespace MagicVilla_Web_new.Controllers
{
    public class VillaNumberController : Controller
    {
        readonly IVillaNumberServices _villaNumberServices;
        readonly IVillaServices _villaServices;
        readonly IMapper _mapper;
        public VillaNumberController(IVillaNumberServices villaNumberServices, IMapper mapper, IVillaServices villaServices)
        {
            _villaNumberServices = villaNumberServices;
            _mapper = mapper;
            _villaServices = villaServices;

            
        }
        public async Task<IActionResult> IndexVillaNumber()
        {
            List<VillaNumberDTO> list = new();
            var response = await _villaNumberServices.GetAllAsync<APIResponse>();
            //if (response != null && response.IsSuccess)
            //{
            list = JsonConvert.DeserializeObject<List<VillaNumberDTO>>(Convert.ToString(response.Result));

            //}
            return View(list);
        }

        public async Task<IActionResult> CreateVillaNumber()
        {
            VillaNumberCreateVM villaNumberVM = new();
            var response = await _villaServices.GetAllAsync<APIResponse>();
            villaNumberVM.villalist = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result)).Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            }); ;
            return View(villaNumberVM);
        }
       

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVillaNumber(VillaNumberCreateVM model)
        {
            if (ModelState.IsValid)
            {
                // Call service method to create the villa number
                var response = await _villaNumberServices.CreatedAsynce<APIResponse>(model.VillaNumber);

                if (response != null && response.IsSuccess)
                {
                    // Redirect to the index action if creation is successful
                    return RedirectToAction(nameof(IndexVillaNumber));
                }
                else
                {
                    // Handle error messages from the response, if any
                    ModelState.AddModelError("ErrorMessages", "Failed to create Villa Number. Please try again later.");
                }
            }

            // Populate the dropdown list of villas
            var resp = await _villaServices.GetAllAsync<APIResponse>();
            if (resp != null && resp.IsSuccess)
            {
                model.villalist = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(resp.Result))
                                    .Select(i => new SelectListItem
                                    {
                                        Text = i.Name,
                                        Value = i.Id.ToString()
                                    });
            }

            // Return the view with the updated model, including any validation errors
            return View(model);
        }







    }
}

MagicVilla_Web_new/Views/VillaNumber/CreateVillaNumber.cshtml
@model MagicVilla_Web_new.Models.VM.VillaNumberCreateVM

<form asp-action="CreateVillaNumber" method="post">
    <div class="container p-3 border rounded shadow-lg">
        <h1 class="text-primary text-center">Create Villa</h1>
        <hr />
        <div class="row text-success">
            <div class="text-danger"></div>
            <div class="col-2">
                <label asp-for="VillaNumber.villaNo" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 p-2 my-1">
                <input asp-for="VillaNumber.villaNo" class="form-control" />
                <span asp-validation-for="VillaNumber.villaNo" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="VillaNumber.villaID" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 p-2 my-1">
                <select asp-for="VillaNumber.villaID" class="form-select" asp-items="@Model.villalist">
                    <option disabled selected>Select item</option>
                </select>
                <span asp-validation-for="VillaNumber.villaID" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="VillaNumber.SpecialDetailes" class="control-label pt-2" style="font-size:20px;"></label>
            </div>
            <div class="col-10 p-2 my-1">
                <textarea asp-for="VillaNumber.SpecialDetailes" class="form-control" rows="6"></textarea>
                <span asp-validation-for="VillaNumber.SpecialDetailes" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-5 offset-2">
                    <a asp-action="IndexVillaNumber" asp-controller="VillaNumber" class="btn-primary btn form-control">Back to List</a>
                </div>
                <div class="col-5">
                    <input type="submit" value="Create" class="btn btn-success form-control" />
                </div>
            </div>
        </div>
    </div>
</form>

MagicVilla_Web_new/Views/VillaNumber/IndexVillaNumber.cshtml
@model IEnumerable<MagicVilla_Web_new.Models.Dto.VillaNumberDTO>

<div class="container p-4 border shadow rounded">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-success">Magic Villa Number List</h1>
        </div>
        <div class="col text-end pt-1">
            <a asp-controller="VillaNumber" asp-action="CreateVillaNumber" class="btn btn-outline-success"><i class="bi bi-shield-fill-plus"></i>Create New (Number)</a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Number</th>
                <th>ID</th>
                
                <th>Name</th>
                <th>Details</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    
                    <td>@item.Villa.Name</td>
                    <td>@item.Villa.Id</td>
                    <td>@item.villaNo</td>
                    <td>@item.SpecialDetailes</td>
                    
                    <td>
                        
                    </td>

                    <td>
                        <a asp-controller="Villa" asp-action="UpdateNumberVilla" asp-route-villaNo="@item.villaNo" class="btn btn-outline-success"> <i class="bi bi-pencil-square"></i>Edit</a>
                        <a asp-controller="Villa" asp-action="DeleteNumberVilla" asp-route-villaNo="@item.villaNo" class="btn btn-outline-danger"><i class="bi bi-trash3-fill"></i>Delete</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>